### ISSUE TITLE
ContainerLogV2 support

### ISSUE THREAD

**Issue by otabut** [ms-sambell/aks-workbook#1]
Hi !

Great and very useful workbook.

Is it planned to add support for ContainerLogV2 ?

Regards.

**Comment by ms-sambell** [comment]
Hey @otabut! 

I will now thank you've asked for it. Give me a few days and I'll add a PR.

**Comment by ms-sambell** [comment]
Added as part of #3

**Comment by ms-sambell** [comment]
Added as part of #3 @otabut
